// app/layout.js
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-gray-100`}>
        <header className="w-full p-4">
          <div className="max-w-7xl mx-auto flex items-center">
            <div className="text-xl font-bold">DevProFolio</div>
          </div>
        </header>
        <main className="max-w-7xl mx-auto p-4">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
